# Version de Docker Compose
version: "3.8"

# Déclaration des services (conteneurs)
services:

  users:
    build: ./microservices/users-service
    ports:
      - "3001:3000"

  orders:
    build: ./microservices/orders-service
    ports:
      - "3002:3000"
      
  # Service base de données MongoDB
  mongo:
    # Image officielle MongoDB
    image: mongo

    # Exposer le port MongoDB
    ports:
      - "27017:27017"

    # Volume pour garder les données même après arrêt du container
    volumes:
      - mongo_data:/data/db

# Déclaration des volumes Docker
volumes:
  mongo_data:   